apiVersion: v1
description: Hybrasyl Server
name: hybrasyl-server
version: 0.9.3
appVersion: 0.9.3
home: https://www.hybrasyl.com
maintainers:
- name: ERISCO, LLC
  url: https://github.com/hybrasyl/server
